# Generated by Django 6.0.4 on 2026-04-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('p_morning', models.FloatField(blank=True, null=True)),
                ('p_noon', models.FloatField(blank=True, null=True)),
                ('p_evening', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
